### ISSUE TITLE
Export to PDF still shows code

### ISSUE THREAD

**Issue by mgcdanny** [kirbs-/hide_code#5]
Hi,

Thanks for the great plug-in.  After I hide the code, the export to pdf still renders code cells.  I am using "File" "Download As" "PDF" from the jupyter notebook browser.

Let me know if you have any suggestions.  My goal is to render the notebook as a pdf without the code cells.  Thanks!

**Comment by kirbs-** [comment]
This plugin uses jQuery to show/hide the various sections. I'm guessing the the pdf exporter is reading directly from the notebook .ipynb file instead of rendering, then exporting. I haven't tried this, but exporting as slides or a html page then saving to pdf may work. 

I'll take a look at this. I'm not that familar with the pdf exporter.

**Comment by kirbs-** [comment]
Looks like the various exporters render directly from the .ipynb file. When I get some time I'll tinker with a custom exporter that respects the code hiding options selected.

**Comment by mgcdanny** [comment]
Cool.  Thanks !

**Comment by cenveoanalyst** [comment]
I use Jupyter Notebooks to write reports in my organization and to hide the code for exporting would be greatly appreciated.

**Comment by kirbs-** [comment]
@mgcdanny @cenveoanalyst I've added support for exporting on the dev branch.  Travis CI is builds are failing on Python 3.x so you may see some problems. Python 2.7 works though.

**Comment by vinhdizzo** [comment]
@kirbs- looking forward to this enhancement.  Just to confirm, when this becomes available, whenever we export the notebook to a different format via jupyter-nbconvert, whatever code or output we hide will be respected in the output file (eg, html), correct?

I'm using Jupyter with the R kernel.  This should also work there, right?  Thanks.

**Comment by kirbs-** [comment]
@vinhdizzo this enhancement adds export options to nbconvert and to Jupyter notebook's UI. I believe it will work with any kernal. Look at the [dev](https://github.com/kirbs-/hide_code/tree/dev) branch for more info.

**Comment by vinhdizzo** [comment]
@kirbs great, I look forward to when this get's rolled into master.  Will test out then.  Thanks again.

**Comment by vinhdizzo** [comment]
Thanks @kirbs- , I just upgraded to 0.2.0 and upgraded nbcovert to 4.2 to test out the new rolled out feature.  My tests:
- The two html and pdf export buttons within the notebook did not work for me (no response)
- `nbconvert --to hide_code_html` did work for me.  My converted html file did indeed hide the raw input code.  However, I still see the `In [  ]:` labels next to empty space.  Is this intended?  Any way to also hide this?

Thanks!

**Comment by kirbs-** [comment]
Can you post the results from the installation process? The first issue sounds like the JS dependencies didn't get installed correctly. On the second issue, did you have the "Hide prompts" option selected?

**Comment by vinhdizzo** [comment]
Second issue: ahh, `Hide Prompt` did fix it.  For some reason I originally thought that referred to `Hide Output`.

`hide_code` upgrade:
```bash
$ pip install --upgrade hide_code
Collecting hide-code
  Downloading hide_code-0.2.0.tar.gz
Requirement already up-to-date: jupyter in c:\programfiles\continuum\anaconda3\lib\site-packages (from hide-code)
Collecting pdfkit (from hide-code)
  Downloading pdfkit-0.5.0.zip
Building wheels for collected packages: hide-code, pdfkit
  Running setup.py bdist_wheel for hide-code: started
  Running setup.py bdist_wheel for hide-code: finished with status 'error'
  Complete output from command C:\ProgramFiles\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\v116795\\AppData\\Local\\Temp\\pip-build-or_oa8cp\\hide-code\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\v116795\AppData\Local\Temp\tmpvnfmvz8vpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\hide_code
  copying hide_code\hide_code.py -> build\lib\hide_code
  copying hide_code\hide_code_html_exporter.py -> build\lib\hide_code
  copying hide_code\hide_code_pdf_exporter.py -> build\lib\hide_code
  copying hide_code\hide_code_preprocessor.py -> build\lib\hide_code
  copying hide_code\__init__.py -> build\lib\hide_code
  copying hide_code\hide_code.js -> build\lib\hide_code
  copying hide_code\auto-load-server-extension.txt -> build\lib\hide_code
  copying hide_code\auto-load.txt -> build\lib\hide_code
  copying hide_code\LICENSE.txt -> build\lib\hide_code
  creating build\lib\hide_code\Templates
  copying hide_code\Templates\hide_code.tpl -> build\lib\hide_code\Templates
  copying hide_code\Templates\hide_code_article.tplx -> build\lib\hide_code\Templates
  copying hide_code\Templates\hide_code_base_style.tplx -> build\lib\hide_code\Templates
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\hide_code
  copying build\lib\hide_code\auto-load-server-extension.txt -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  copying build\lib\hide_code\auto-load.txt -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  copying build\lib\hide_code\hide_code.js -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  copying build\lib\hide_code\hide_code.py -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  copying build\lib\hide_code\hide_code_html_exporter.py -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  copying build\lib\hide_code\hide_code_pdf_exporter.py -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  copying build\lib\hide_code\hide_code_preprocessor.py -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  copying build\lib\hide_code\LICENSE.txt -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  creating build\bdist.win-amd64\wheel\hide_code\Templates
  copying build\lib\hide_code\Templates\hide_code.tpl -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code\Templates
  copying build\lib\hide_code\Templates\hide_code_article.tplx -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code\Templates
  copying build\lib\hide_code\Templates\hide_code_base_style.tplx -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code\Templates
  copying build\lib\hide_code\__init__.py -> build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code
  running install_egg_info
  running egg_info
  writing top-level names to hide_code.egg-info\top_level.txt
  writing requirements to hide_code.egg-info\requires.txt
  writing entry points to hide_code.egg-info\entry_points.txt
  writing dependency_links to hide_code.egg-info\dependency_links.txt
  writing hide_code.egg-info\PKG-INFO
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'hide_code.egg-info\SOURCES.txt'
  writing manifest file 'hide_code.egg-info\SOURCES.txt'
  Copying hide_code.egg-info to build\bdist.win-amd64\wheel\hide_code-0.2.0.data\..\hide_code-0.2.0-py3.5.egg-info
  running install_scripts
  Running post install task...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\v116795\AppData\Local\Temp\pip-build-or_oa8cp\hide-code\setup.py", line 118, in <module>
      'hide_code_pdf = hide_code:HideCodePDFExporter',
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 212, in run
      self.run_command('install')
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\v116795\AppData\Local\Temp\pip-build-or_oa8cp\hide-code\setup.py", line 29, in run
      self.execute(_post_install, (self.install_lib, ), msg="Running post install task...")
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\distutils\cmd.py", line 336, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "C:\ProgramFiles\Continuum\Anaconda3\lib\distutils\util.py", line 301, in execute
      func(*args)
    File "C:\Users\v116795\AppData\Local\Temp\pip-build-or_oa8cp\hide-code\setup.py", line 13, in _post_install
      from hide_code import hide_code
    File "c:\users\v116795\appdata\local\temp\pip-build-or_oa8cp\hide-code\hide_code\hide_code.py", line 10, in <module>
      import pdfkit
  ImportError: No module named 'pdfkit'

  ----------------------------------------
  Failed building wheel for hide-code
  Running setup.py clean for hide-code
  Running setup.py bdist_wheel for pdfkit: started
  Running setup.py bdist_wheel for pdfkit: finished with status 'done'
  Stored in directory: C:\Users\v116795\AppData\Local\pip\Cache\wheels\8e\fe\d0\ef49740186cbeece01d2bdc87a7a6903f0dfd6c256b5421446
Successfully built pdfkit
Failed to build hide-code
Installing collected packages: pdfkit, hide-code
  Found existing installation: hide-code 0.1.6
    Uninstalling hide-code-0.1.6:
      Successfully uninstalled hide-code-0.1.6
  Running setup.py install for hide-code: started
    Running setup.py install for hide-code: finished with status 'done'
Successfully installed hide-code-0.2.0 pdfkit-0.5.0
You are using pip version 8.0.2, however version 8.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by vinhdizzo** [comment]
BTW, I just tried the export button again, and I get
```
404 : Not Found
You are requesting a page that does not exist!
```

**Comment by kirbs-** [comment]
Try running 
```python
import hide_code.hide_code as hc
hc.install()
```

**Comment by vinhdizzo** [comment]
```python
Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import hide_code.hide_code as hc
hc.install()
>>> Starting hide_code.js install...
No config directories contain "custom" folder. Trying site-packages...
Copying hide_code.js to C:\ProgramFiles\Continuum\Anaconda3\lib\site-packages\notebook/static/custom
Attempting to configure custom.js to auto-load hide__code.js...
Custom.js already configured to auto-load hide_code.js.
Attempting to configure default profile to auto-load hide_code export handlers.
jupyter_notebook_config already configured to auto-load export handlers.
>>>
```

**Comment by kirbs-** [comment]
Do you see hide_code.js in C:\ProgramFiles\Continuum\Anaconda3\lib\site-packages\notebook\static\custom ?

**Comment by vinhdizzo** [comment]
Yes, I see `custom.css`, `custom.js`, and `hide_code.js`.

**Comment by kirbs-** [comment]
Does pip show hide_code as version 0.2.0?

**Comment by vinhdizzo** [comment]
It did when I installed it.  Here it is when I just checked:
```bash
$ pip freeze | grep hide
hide-code==0.2.0
```

Note that when I use `jupyter-nbconvert --to hide_code_html`, things work.  It's just that button that doesn't work.  Thanks.

**Comment by kirbs-** [comment]
Odd, are you getting any JS errors when you click on either export button?

**Comment by vinhdizzo** [comment]
No.  In the jupyter console, all I see is:
```
404 GET /notebooks/path/to/Untitled.ipynb/export/html
```

**Comment by kirbs-** [comment]
The installation didn't run smoothly, so I'm guessing the export handlers for Jupyter notebook didn't load correctly. Run the code below from any notebook.
```python
from notebook.services.config import ConfigManager
import jupyter_core.paths as j_path
server_cm = ConfigManager(config_dir=j_path.jupyter_config_dir())
print(server_cm.get('jupyter_notebook_config'))
```
You should see this if the export handlers are enabled.
`
{u'NotebookApp': {u'server_extensions': [u'hide_code.hide_code']}}
`
Also, just to confirm, did you restart Jupyter after upgrading hide code?

**Comment by vinhdizzo** [comment]
Yes, I did restart Jupyter after upgrading hide_code.  I just did it again.  Within a notebook cell, I get:
```
Error in parse(text = x, srcfile = src): <text>:1:6: unexpected symbol
1: from notebook.services.config
```

When I open a python interpreter and run your code, I do get
```
{'NotebookApp': {'server_extensions': ['hide_code.hide_code']}}
```

**Comment by kirbs-** [comment]
Definitely sounds like the export handlers didn't load. Try starting jupyter using
`
jupyter notebook --NotebookApp.server_extensions="['hide_code.hide_code']"
`

**Comment by vinhdizzo** [comment]
Same problem persists.  Here's the console log:
```
$ jupyter-notebook --NotebookApp.server_extensions="['hide_code.hide_code']"
[W 14:55:35.842 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 14:55:36.418 NotebookApp] Serving notebooks from local directory: C:\Users\my_id
[I 14:55:36.418 NotebookApp] 0 active kernels
[I 14:55:36.418 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 14:55:36.418 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:55:52.015 NotebookApp] Kernel started: b7bd56ed-97c5-4cb8-a587-ed090dbcbc8d
[1] "Got unhandled msg_type:" "comm_open"
[W 14:56:04.750 NotebookApp] 404 GET /notebooks/Projects/Untitled.ipynb/export/html (::1): No such file or directory: Projects/Untitled.ipynb/export/html
[W 14:56:04.758 NotebookApp] 404 GET /notebooks/Projects/Untitled.ipynb/export/html (::1) 8.00ms referer=http://localhost:8888/notebooks/Projects/Untitled.ipynb
```

**Comment by kirbs-** [comment]
I just pushed v0.2.1. I added some logging to the release to help troubleshoot. Would you upgrade, restart Jupyter, try exporting and past the results. Also run the code below:
```python
import hide_code as hc
print hc.setup_info()
```

**Comment by vinhdizzo** [comment]
Here's the upgrade:
```
$ pip install --upgrade hide_code
Collecting hide-code
  Downloading hide_code-0.2.1.tar.gz
Requirement already up-to-date: jupyter in c:\programfiles\continuum\anaconda3\lib\site-packages (from hide-code)
Requirement already up-to-date: pdfkit in c:\programfiles\continuum\anaconda3\lib\site-packages (from hide-code)
Building wheels for collected packages: hide-code
  Running setup.py bdist_wheel for hide-code: started
  Running setup.py bdist_wheel for hide-code: finished with status 'done'
  Stored in directory: C:\Users\v116795\AppData\Local\pip\Cache\wheels\5d\db\b0\5d1003c4d3b7345c4bc650c720c9cd2421c9fb4d7d6ea63860
Successfully built hide-code
Installing collected packages: hide-code
  Found existing installation: hide-code 0.2.0
    Uninstalling hide-code-0.2.0:
      Successfully uninstalled hide-code-0.2.0
Successfully installed hide-code-0.2.1
```

I just realized something I forgot to mention (stupid me, apologies).  I've been using the R kernel, and hence those python debug messages did not run before.  Here it is with the Python3 kernel:
```
from notebook.services.config import ConfigManager
import jupyter_core.paths as j_path
server_cm = ConfigManager(config_dir=j_path.jupyter_config_dir())
print(server_cm.get('jupyter_notebook_config'))
{'NotebookApp': {'server_extensions': ['hide_code.hide_code']}}

import hide_code as hc
print(hc.setup_info())
Installation dir: C:\ProgramFiles\Continuum\Anaconda3\lib\site-packages
Configuration dir:C:\Users\My\Home\Path\.jupyter
Export handler extensions: Loaded
Hide Code files: ['auto-load-server-extension.txt', 'auto-load.txt', 'hide_code.js', 'hide_code.py', 'hide_code_html_exporter.py', 'hide_code_pdf_exporter.py', 'hide_code_preprocessor.py', 'LICENSE.txt', '__init__.py']
Custom JS contents: 
 define([
 'base/js/events'
 ], 
 function(events) {
     events.on('app_initialized.NotebookApp', function(){
         require(['custom/hide_code']);
     });
 }); 
```

When I click the export button, I get a popup that says `I couldn't find a kernel matching python3/export/html/export/html.  Please select a kernel: [Choose Python 3 or R]`

So, maybe it's not working because `hide_code` only works with the `python2` kernel?

**Comment by kirbs-** [comment]
Thanks, hide_code installed cleanly for you. I tested exporting with R kernel. The routes used by the R kernel aren't defined. This is a bug in hide_code's routing. I'll get this updated. If you delete `?kernel_name=ir` from the url, then click an export button it works.

**Comment by vinhdizzo** [comment]
I don't see `?kernel_name=ir` in my notebook's url.  Maybe this is a `python3` thing?

Also, based on my previous results, it appears that `hide_code` does not work with `python3` kernel?

**Comment by kirbs-** [comment]
I've fixed the routing bug on the dev branch. Would you download, unzip, and run `python setup.py install` from the directory?

It should work with all kernels. I've tested with python 2.7, 3.5 and now R; everything works as expected.

**Comment by vinhdizzo** [comment]
Hmm, still not working on the R kernel or python3 kernel (404 file not found).  Here's my install log:
```
$ /cygdrive/c/ProgramFiles/Continuum/Anaconda3/python setup.py install
running install
running build
running build_py
running install_lib
running install_egg_info
running egg_info
writing dependency_links to hide_code.egg-info\dependency_links.txt
writing requirements to hide_code.egg-info\requires.txt
writing hide_code.egg-info\PKG-INFO
writing top-level names to hide_code.egg-info\top_level.txt
writing entry points to hide_code.egg-info\entry_points.txt
reading manifest file 'hide_code.egg-info\SOURCES.txt'
writing manifest file 'hide_code.egg-info\SOURCES.txt'
removing 'C:\ProgramFiles\Continuum\Anaconda3\Lib\site-packages\hide_code-0.2.2-py3.5.egg-info' (and everything under it)
Copying hide_code.egg-info to C:\ProgramFiles\Continuum\Anaconda3\Lib\site-packages\hide_code-0.2.2-py3.5.egg-info
running install_scripts
Running post install task...
Starting hide_code.js install...
No config directories contain "custom" folder. Trying site-packages...
Copying hide_code.js to C:\ProgramFiles\Continuum\Anaconda3\lib\site-packages\notebook\static\custom
Attempting to configure custom.js to auto-load hide__code.js...
Custom.js already configured to auto-load hide_code.js.
Attempting to configure auto-loading for hide_code export handlers.
Jupyter already configured to auto-load export handlers.
```
In the Jupyter console, in addition to the `404 GET` error, I see:
```
[1] "Got unhandled msg_type:" "comm_open"
```

**Comment by kirbs-** [comment]
I noticed in here 

> [W 14:56:04.750 NotebookApp] 404 GET /notebooks/**_Projects/Untitled.ipynb_**/export/html (::1): No such file or directory: Projects/Untitled.ipynb/export/html

you're testing with a notebook nested in the root directory. I found another routing issue with this use case. I've pushed a fix to the dev branch. Would you download, unzip, install and retest?

**Comment by vinhdizzo** [comment]
Still doesn't work for me.  In Jupyter console:
```
No such file or directory: Folder1/Projects/Untitled.ipynb/export/html
```

**Comment by kirbs-** [comment]
What the full URL you see with a notebook open? I only implemented support for one child folder level. For example: `juypter_root/some_folder/some_notebook.ipynb` should work, but `juypter_root/some_folder/another_folder/some_notebook.ipynb` will not.

**Comment by vinhdizzo** [comment]
URL: `http://localhost:8888/notebooks/Folder1/Projects/Untitled1.ipynb/export/html`
Based on what you stated, this is not supported?

I copied the file into Folder1, and yes, the export button works.

**Comment by kirbs-** [comment]
Glad that finally worked. The plugin will support any number of nested folders. I just set it to two levels deep to troubleshoot your issue. I'll get this fixed for the next release.

**Comment by kirbs-** [comment]
This is resolved in 0.3.0.

**Comment by vinhdizzo** [comment]
Thanks, confirming both the 'export to html' and 'export to pdf via 'wkhtmltopdf' works for me.
